# example3: a time series with 2 clusters

rm(list=ls(all=TRUE))

library(PMLseg)

simulate_time_series <- function(jump_ind, segmt_mean, noise_stdev, length_series) {
  time_series <- rep(0, length_series)
  jump_indices <- c(1, jump_ind+1, length_series + 1)
  offsets <- c(0, diff(segmt_mean))
  
  changes <- rep(0, length_series)
  changes[jump_indices[-length(jump_indices)]] <- offsets
  changes[1] <- segmt_mean[1]
  
  time_series <- cumsum(changes)
  noise <- rnorm(n = length_series, mean = 0, sd = noise_stdev)
  time_series <- time_series + noise
  
  return(time_series)
}

n = 1000
jump_ind <- c(10, 200, 210, 580, 590, 600, 990)   # 2 clusters of CPs + one short segment at the begining and one at the end
segmt_mean <- c(0, -1, 5, 1, -5, 5, 2, 0)
noise_stdev = 1
valid_max_dist = 62         # validation parameter
cluster_max_dist = 80       # screening parameter
set.seed(1)

mydate <- seq.Date(from = as.Date("2010-01-01"), to = as.Date("2010-01-01")+(n-1), by = "day")
mysignal <- simulate_time_series(jump_ind, segmt_mean, noise_stdev, n)

df = data.frame(date = mydate, signal = mysignal)
plot(df$date, df$signal, type = "l")

seg = Segmentation(OneSeries = df, FunctPart = FALSE)
seg

PlotSeg(OneSeries = df, SegRes = seg, FunctPart = FALSE)

# Create metadata for the true CP positions
truth = data.frame(date = df$date[jump_ind], type = rep("True", (length(jump_ind))))

# validate estimated CP position wrt metadata
valid = Validation(OneSeries = df, Tmu = seg$Tmu, MinDist = valid_max_dist, Metadata = truth)

screening = Cluster_screening(Tmu = seg$Tmu, MaxDist = cluster_max_dist)
screening

# update the time series 
df_screened <- df
for (i in 1:(length(screening$RemoveData))) {
    df_screened$signal[screening$RemoveData$begin[i]:screening$RemoveData$end[i]] = NA
}

# update the segmentation parameters
seg_updated = UpdatedParametersForFixedCP(OneSeries = df, ResScreening = screening, FunctPart=FALSE)
seg_updated

# Explore the plot options
PlotSeg(OneSeries = df_screened, SegRes = seg_updated, FunctPart = FALSE)

PlotSeg(OneSeries = df, SegRes = seg_updated, FunctPart = FALSE, RemoveData = screening$RemoveData)

PlotSeg(OneSeries = df, SegRes = seg_updated, FunctPart = FALSE, RemoveData = screening$RemoveData, Metadata = truth) 

PlotSeg(OneSeries = df, SegRes = seg_updated, FunctPart = FALSE, RemoveData = screening$RemoveData, Metadata = truth, Validated_CP_Meta = valid)

# validate updated CP position wrt metadata
valid = Validation(OneSeries = df, Tmu = seg_updated$Tmu, MinDist = valid_max_dist, Metadata = truth)
valid

PlotSeg(OneSeries = df, SegRes = seg_updated, FunctPart = FALSE, RemoveData = screening$RemoveData, Metadata = truth, Validated_CP_Meta = valid)
