# example5: a time series with periodic bias

rm(list=ls(all=TRUE))

library(PMLseg)

simulate_time_series <- function(cp_ind, segmt_mean, noise_stdev, length_series) {
  time_series <- rep(0, length_series)
  cp_indices <- c(1, cp_ind, length_series + 1)
  offsets <- c(0, diff(segmt_mean))
  
  changes <- rep(0, length_series)
  changes[cp_indices[-length(cp_indices)]] <- offsets
  changes[1] <- segmt_mean[1]
  time_series <- cumsum(changes)
  
  sd = noise_stdev[as.numeric(format(mydate, "%m"))]
  noise <- rnorm(n = length_series, mean = 0, sd = 1)
  time_series <- time_series + noise * sd
  
  return(time_series)
}

# specify time series simulation parameters
date_begin <- as.Date("2010-03-01") # date of first data point
n = 1000                            # length of time series
cp_ind <- c(200, 600)               # position of change points (index in time series)
segmt_mean <- c(-1, 1, 2)           # mean value of segments
noise_stdev <- rep(0.1, 12)           # noise variance (Jan to Dec)
coeff <- c(1, 0, 0, 0)              # Fourier series coefficients (cos1, sin1, cos2, sin2...)

# create a time series df with jumps and noise
set.seed(1)
mydate <- seq.Date(from = date_begin, to = date_begin + n - 1, by = "day")
mysignal <- simulate_time_series(cp_ind, segmt_mean, noise_stdev, n)

# create a periodic function (Fourier series)
date_periodic <- date_begin
# date_periodic <- as.Date("2010-01-01") # reference date of periodic function
T = 365.25                             # reference period (unit days)
t = as.numeric(mydate)
t0 = as.numeric(date_periodic)
p = length(coeff) / 2
f = rowSums(sapply(1:p, function(i) coeff[2*i-1]*cos(i*(t-t0)*(2*pi)/T) + coeff[2*i]*sin(i*(t-t0)*(2*pi)/T)))
plot(mydate, f, type = "l")

# full signal
mysignal <- mysignal + f
df = data.frame(date = mydate, signal = mysignal)
plot(df$date, df$signal, type = "l")

# run segmentation
seg = Segmentation(OneSeries = df, FunctPart = TRUE)
seg$Tmu
seg$CoeffF
seg$MonthVar
seg$SSR
